<?xml version="1.0" encoding="utf-8"?><Database Name="QLCafe" Class="QLCFDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HP090123\SQLEXPRESS;Initial Catalog=QLCafe;Integrated Security=True" SettingsObjectName="DAL_BLL.Properties.Settings" SettingsPropertyName="QLCafeConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ban" Member="Bans">
    <Type Name="Ban">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Ban_DonHang" Member="DonHangs" ThisKey="ID" OtherKey="IDTable" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.Topping" Member="Toppings">
    <Type Name="Topping">
      <Column Name="MaTopping" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Topping_ChiTietTopping" Member="ChiTietToppings" ThisKey="MaTopping" OtherKey="MaTopping" Type="ChiTietTopping" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaChiTietDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietTopping" Member="ChiTietToppings">
    <Type Name="ChiTietTopping">
      <Column Name="MaChiTietTopping" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTopping" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Topping_ChiTietTopping" Member="Topping" ThisKey="MaTopping" OtherKey="MaTopping" Type="Topping" IsForeignKey="true" />
      <Association Name="DonHang_ChiTietTopping" Member="DonHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="IDTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietDonHang" />
      <Association Name="DonHang_ChiTietTopping" Member="ChiTietToppings" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietTopping" />
      <Association Name="Ban_DonHang" Member="Ban" ThisKey="IDTable" OtherKey="ID" Type="Ban" IsForeignKey="true" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_DonHang" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_DonHang" Member="DonHangs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="DonHang" />
      <Association Name="NhanVien_tbl_per_relationship" Member="tbl_per_relationships" ThisKey="MaNhanVien" OtherKey="id_user_rel" Type="tbl_per_relationship" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDonHang" />
      <Association Name="TheLoai_SanPham" Member="TheLoai" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_per_relationship" Member="tbl_per_relationships">
    <Type Name="tbl_per_relationship">
      <Column Name="id_rel" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user_rel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_per_rel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="suspended" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NhanVien_tbl_per_relationship" Member="NhanVien" ThisKey="id_user_rel" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="tbl_permision_tbl_per_relationship" Member="tbl_permision" ThisKey="id_per_rel" OtherKey="id_per" Type="tbl_permision" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_permision" Member="tbl_permisions">
    <Type Name="tbl_permision">
      <Column Name="id_per" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_per" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_permision_tbl_per_relationship" Member="tbl_per_relationships" ThisKey="id_per" OtherKey="id_per_rel" Type="tbl_per_relationship" />
      <Association Name="tbl_permision_tbl_permision_del" Member="tbl_permision_dels" ThisKey="id_per" OtherKey="id_per" Type="tbl_permision_del" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_permision_del" Member="tbl_permision_dels">
    <Type Name="tbl_permision_del">
      <Column Name="id_pd" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code_action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id_per" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_permision_tbl_permision_del" Member="tbl_permision" ThisKey="id_per" OtherKey="id_per" Type="tbl_permision" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="TheLoai_SanPham" Member="SanPhams" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="SanPham" />
    </Type>
  </Table>
</Database>